ndncat put /ndn/video/master.m3u8 --file=master.m3u8 --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_0.m3u8 --file=stream_0.m3u8 --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_1.m3u8 --file=stream_1.m3u8 --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_2.m3u8 --file=stream_2.m3u8 --chunk-size=8192 --ver=none &> /dev/null &

ndncat put /ndn/video/stream_0/data00.ts --file=stream_0/data00.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_0/data01.ts --file=stream_0/data01.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_0/data02.ts --file=stream_0/data02.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_0/data03.ts --file=stream_0/data03.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_0/data04.ts --file=stream_0/data04.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_0/data05.ts --file=stream_0/data05.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_0/data06.ts --file=stream_0/data06.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_0/data07.ts --file=stream_0/data07.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_0/data08.ts --file=stream_0/data08.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_0/data09.ts --file=stream_0/data09.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_0/data10.ts --file=stream_0/data10.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_0/data11.ts --file=stream_0/data11.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_0/data12.ts --file=stream_0/data12.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_0/data13.ts --file=stream_0/data13.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_0/data14.ts --file=stream_0/data14.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_1/data00.ts --file=stream_1/data00.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_1/data01.ts --file=stream_1/data01.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_1/data02.ts --file=stream_1/data02.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_1/data03.ts --file=stream_1/data03.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_1/data04.ts --file=stream_1/data04.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_1/data05.ts --file=stream_1/data05.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_1/data06.ts --file=stream_1/data06.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_1/data07.ts --file=stream_1/data07.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_1/data08.ts --file=stream_1/data08.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_1/data09.ts --file=stream_1/data09.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_1/data10.ts --file=stream_1/data10.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_1/data11.ts --file=stream_1/data11.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_1/data12.ts --file=stream_1/data12.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_1/data13.ts --file=stream_1/data13.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_1/data14.ts --file=stream_1/data14.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_2/data00.ts --file=stream_2/data00.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_2/data01.ts --file=stream_2/data01.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_2/data02.ts --file=stream_2/data02.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_2/data03.ts --file=stream_2/data03.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_2/data04.ts --file=stream_2/data04.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_2/data05.ts --file=stream_2/data05.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_2/data06.ts --file=stream_2/data06.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_2/data07.ts --file=stream_2/data07.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_2/data08.ts --file=stream_2/data08.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_2/data09.ts --file=stream_2/data09.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_2/data10.ts --file=stream_2/data10.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_2/data11.ts --file=stream_2/data11.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_2/data12.ts --file=stream_2/data12.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_2/data13.ts --file=stream_2/data13.ts --chunk-size=8192 --ver=none &> /dev/null &
ndncat put /ndn/video/stream_2/data14.ts --file=stream_2/data14.ts --chunk-size=8192 --ver=none &> /dev/null &
